on:
 push:
  branches:
   - main
 
name: Push the Docker image to AWS ECR Repo

jobs:
 Build:
  name: Build
  runs-on: ubuntu-latest
  permissions:
   id-token: write
   contents: read
  steps:
   - name: Checkout
     uses: actions/checkout@v2
     
   - name: Configure AWS Credentials Action for GitHub Actions
     uses: aws-actions/configure-aws-credentials@v4.0.2
     with:
      role-to-assume: ${{ secrets.IAM_GHA_ROLE }}
      role-session-name: GitHub_to_AWS_via_FederatedOIDC
      aws-region: us-east-1
      
   - name: Login to Amazon ECR
     id: login-ecr
     uses: aws-actions/amazon-ecr-login@v1

   - name: Build, tag, and push the image to Amazon ECR
     id: build-image
     env:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
      IMAGE_TAG: latest
     run: |
      docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
      docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
